### ISSUE TITLE
yabause (saturn emulator) fail buil if use hardening-wrapper

### ISSUE THREAD

**Issue by sl1pkn07** [thestinger/hardening-wrapper#1]
Hi, if build yabause 0.9.14 or git, if have installed hardening-wrapper, fail build with

http://sl1pkn07.wtf/paste/view/b5de3a7b

adding 

```
CFLAGS+=" -fPIC"
CXXFLAGS+=" -fPIC"
```

don't work

if remove hardening-wrapper, build ok

How I can see if it is necessary or not the wrapper?

greetings

**Comment by thestinger** [comment]
If it depends on static libraries, then those need to be built with hardening-wrapper too.

**Comment by thestinger** [comment]
PIE requires that all code in the executable is compiled with either `-fPIC` or `-fPIE` and static libraries built without hardening-wrapper won't usually have either.

**Comment by sl1pkn07** [comment]
not use external static libs, build internal .a and then build the executable with him

**Comment by thestinger** [comment]
hardening-wrapper is now deprecated as Arch will be adopting these features in the standard toolchain.
