### ISSUE TITLE
32-bit Qt 4 build fails

### ISSUE THREAD

**Issue by Alexander-Shukaev** [thestinger/hardening-wrapper#11]
Try one from AUR.  It configures the QMake build system to produce a 32-bit build but looks like due to hardening wrapper still wrongly caches somewhere that it's on 64-bit system.  As a result, the first part of the build is done for 32-bit, but when it comes to building `QtCore`'s inline assembly, it complains about nonsensical (for 32-bit targets) 64-bit registers being referenced.

**Comment by thestinger** [comment]
hardening-wrapper is now deprecated as Arch will be adopting these features in the standard toolchain.
