### ISSUE TITLE
relative include of common.sh breaks OpenWRT buildroot

### ISSUE THREAD

**Issue by octomike** [thestinger/hardening-wrapper#4]
There is general problem with the relative include line in cc-wrapper.sh.

 https://github.com/thestinger/hardening-wrapper/blob/master/cc-wrapper.sh#L3

It seems that at least OpenWRT is tripping over this as it is symlinking gcc inside their own directories.

**Comment by thestinger** [comment]
hardening-wrapper is now deprecated as Arch will be adopting these features in the standard toolchain.
