### ISSUE TITLE
Doesn't respect CC or CXX flags in Archlinux

### ISSUE THREAD

**Issue by ilikenwf** [thestinger/hardening-wrapper#7]
Arch defaults to using hardening-wrapper, which would be fine if it didn't break packages incompatible with gcc6, as there are gcc6 specific bins inside the hardening wrapper directory.

For multi-compiler systems, it would be nice if CC and CXX were respected since Arch is forcing this.

**Comment by thestinger** [comment]
It intercepts calls to 'gcc' and then redirects them to 'gcc'. It doesn't have any impact on multiple compiler systems.
