### ISSUE TITLE
Fails silently when env PATH doesn't contain /path/to/hardening-wrapper/bin

### ISSUE THREAD

**Issue by GrenouilleToxique** [thestinger/hardening-wrapper#8]
Hello,

Let PATH worth "/bin:/usr/bin" (as for example, after bash <= 4.3 "command -p" 's bogus behavior)
Then execute /usr/lib/hardening-wrapper/bin/cc

Actual result : fails silently to execute /usr/bin/cc (common.sh executes "false" instead).
Expected result : execute /usr/bin/cc, and/or print a message to help figuring out there's a PATH issue.

Real world scenario : https://github.com/cryfs/cryfs/issues/102

**Comment by thestinger** [comment]
hardening-wrapper is now deprecated as Arch will be adopting these features in the standard toolchain.
