### ISSUE TITLE
Feture request: Add a wrapper for the go executable

### ISSUE THREAD

**Issue by xyproto** [thestinger/hardening-wrapper#9]
Hi Daniel,

`/usr/bin/go` in the `go` package in Arch Linux supports the `-buildmode=pie` argument.

While PIE is not as critical for security for Go executables as for C executables, it might be nice to have the option of also hardening Go package just by depending on `hardening-wrapper` (it's a nifty idea in the first place!).

Please consider adding a wrapper script for go as well.

There's a related discussion at this bug report: https://bugs.archlinux.org/task/53087

Best regards,
Alexander F Rødseth

**Comment by thestinger** [comment]
hardening-wrapper is now deprecated as Arch will be adopting these features in the standard toolchain.
